### ISSUE TITLE
Limitations & Scope for this project?

### ISSUE THREAD

**Issue by l-k22** [eGust/epub-package.dart#1]
Hi I just noticed this package, I was wondering if this was purely a reader or is there a widget to display the content, flip through pages, bookmark and search, or if you had planned to implement this in the future?

Thanks

**Comment by eGust** [comment]
This repo is not about a UI component for epub. It's dealing with the epub file format.

If you are interested in how to display it, I always do that work in a web way: html + css + js. 
I am writing a [reader](https://github.com/eGust/epub-shelf.flutter) now but not actively, since the WebView component I am using does not support ios yet. It can display and flip now. To display toc is my next task and sure I will have some bookmarks functionality. But not sure about searching.

**Comment by eGust** [comment]
Closed since no feedback
